#pragma once
#include <vector>
#include <iostream>
#include <map>
#include <algorithm>
#include <stack>
#include "Solution.h"

using namespace std;

/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example:
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.
*/

/*
"abcd"
"abcde"
*/

char findTheDifference(string s, string t) {
	map<char, int> sRecord;

	for (int i = 0; i < s.length(); i++)
	{
		sRecord[s[i]]++;
	}

	for (int i = 0; i < t.length(); i++)
	{
		if (sRecord[t[i]] > 0)
			sRecord[t[i]]--;
		else
			return t[i];
	}

	return '.';
}